package com.inksoul.entity;

import javax.persistence.*;
import javax.validation.constraints.NotNull;

/**
 * 文章更新记录实体类
 * 
 * @author InkSoul Team
 */
@Entity
@Table(name = "article_updates", indexes = {
    @Index(name = "idx_update_article_id", columnList = "article_id"),
    @Index(name = "idx_update_created_at", columnList = "created_at")
})
public class ArticleUpdate extends BaseEntity {

    @NotNull(message = "文章不能为空")
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "article_id", nullable = false)
    private GeneratedArticle article;

    @Enumerated(EnumType.STRING)
    @Column(name = "update_type", nullable = false, length = 20)
    private UpdateType updateType;

    @Column(name = "previous_content", columnDefinition = "TEXT")
    private String previousContent; // 更新前的内容

    @Column(name = "new_content", columnDefinition = "TEXT")
    private String newContent; // 更新后的内容

    @Column(name = "added_entries", columnDefinition = "TEXT")
    private String addedEntries; // JSON格式存储新增的日记条目ID

    @Column(name = "update_summary", length = 500)
    private String updateSummary; // 更新摘要

    @Column(name = "auto_generated")
    private Boolean autoGenerated = false; // 是否为自动生成的更新

    // 更新类型枚举
    public enum UpdateType {
        APPEND("追加"),
        INTEGRATE("整合"),
        REWRITE("重写"),
        MANUAL("手动编辑");

        private final String description;

        UpdateType(String description) {
            this.description = description;
        }

        public String getDescription() {
            return description;
        }
    }

    // Constructors
    public ArticleUpdate() {}

    public ArticleUpdate(GeneratedArticle article, UpdateType updateType) {
        this.article = article;
        this.updateType = updateType;
    }

    // Getters and Setters
    public GeneratedArticle getArticle() {
        return article;
    }

    public void setArticle(GeneratedArticle article) {
        this.article = article;
    }

    public UpdateType getUpdateType() {
        return updateType;
    }

    public void setUpdateType(UpdateType updateType) {
        this.updateType = updateType;
    }

    public String getPreviousContent() {
        return previousContent;
    }

    public void setPreviousContent(String previousContent) {
        this.previousContent = previousContent;
    }

    public String getNewContent() {
        return newContent;
    }

    public void setNewContent(String newContent) {
        this.newContent = newContent;
    }

    public String getAddedEntries() {
        return addedEntries;
    }

    public void setAddedEntries(String addedEntries) {
        this.addedEntries = addedEntries;
    }

    public String getUpdateSummary() {
        return updateSummary;
    }

    public void setUpdateSummary(String updateSummary) {
        this.updateSummary = updateSummary;
    }

    public Boolean getAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(Boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }
}